version: 0.2

env:
  variables:
    IMAGE_NAME: deployment-check-cicd

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
      - echo Building Docker image...
	  - pwd
	  - ls -la
	  - cat Dockerfile || echo "Dockerfile not found!"
      - docker build -t $IMAGE_NAME .

  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - target/deployment-check-cicd.jar
  discard-paths: yes
